
apiVersion: v1
kind: Service
metadata:
  name: safechain-backend
  namespace: safechain-mk
  labels:
    app.kubernetes.io/name: safechain-backend
    app.kubernetes.io/part-of: safechain-mk
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: safechain-backend
  ports:
    - name: http
      port: 8787
      targetPort: 8787
