
apiVersion: v1
kind: ConfigMap
metadata:
  name: safechain-backend-config
  namespace: safechain-mk
  labels:
    app.kubernetes.io/name: safechain-backend
    app.kubernetes.io/part-of: safechain-mk
data:
  PORT: "8787"
  HOST: "0.0.0.0"
  NODE_ENV: "production"
  MONGODB_DB_NAME: "safecity_mk"
  DEMO_FALLBACK: "true"
  PUBLIC_DEMO_CODES_ENABLED: "true"
