
apiVersion: v1
kind: Secret
metadata:
  name: safechain-backend-secrets
  namespace: safechain-mk
  labels:
    app.kubernetes.io/name: safechain-backend
    app.kubernetes.io/part-of: safechain-mk
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYjovL3NhZmVjaGFpbl9hZG1pbjpEZW1vLUNoYW5nZU1lLTIwMjYlMjFAc2FmZWNoYWluLW1vbmdvLWhlYWRsZXNzLnNhZmVjaGFpbi1tay5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy9zYWZlY2l0eV9taz9hdXRoU291cmNlPWFkbWlu
  SECURITY_CODE_PEPPER: azhzLWRlbW8tcGVwcGVyLWNoYW5nZS1pbi1yZWFsLWRlcGxveW1lbnQ=
  MEMO_ENCRYPTION_KEY: OGY5YjM4MjI0MWZkZDY4MWFhNTRjN2RhNmRhYmQ5NjBhYWI5M2U3ODQyMGM5MmQxMTQ3MjlmYmFkZDdmN2E4Mg==
  ADMIN_TOKEN: MmM3ZTk2ODkxMmRkNTg4YWIxMmI2NTg2YzIzYTU3OTY=
