
apiVersion: v1
kind: Service
metadata:
  name: safechain-frontend
  namespace: safechain-mk
  labels:
    app.kubernetes.io/name: safechain-frontend
    app.kubernetes.io/part-of: safechain-mk
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: safechain-frontend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
