
apiVersion: v1
kind: Secret
metadata:
  name: safechain-mongo-credentials
  namespace: safechain-mk
  labels:
    app.kubernetes.io/name: safechain-mongo
    app.kubernetes.io/part-of: safechain-mk
type: Opaque
data:
  MONGO_ROOT_USERNAME: c2FmZWNoYWluX2FkbWlu
  MONGO_ROOT_PASSWORD: RGVtby1DaGFuZ2VNZS0yMDI2IQ==
