
apiVersion: v1
kind: ConfigMap
metadata:
  name: safechain-mongo-config
  namespace: safechain-mk
  labels:
    app.kubernetes.io/name: safechain-mongo
    app.kubernetes.io/part-of: safechain-mk
data:
  MONGO_DB_NAME: "safecity_mk"
  MONGO_PORT: "27017"
